# Generated by Django 4.2.10 on 2025-04-21 20:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import osint_geospy.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DroneImage',
            fields=[
                ('image_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to=osint_geospy.models.get_upload_path)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('camera_make', models.CharField(blank=True, max_length=255)),
                ('camera_model', models.CharField(blank=True, max_length=255)),
                ('analyzed', models.BooleanField(default=False)),
                ('analysis_result', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_id', models.CharField(max_length=50)),
                ('related_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='osint_geospy.droneimage')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('result_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('neighborhood', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('confidence', models.CharField(blank=True, max_length=50)),
                ('architectural_features', models.JSONField(blank=True, default=list)),
                ('landscape_features', models.JSONField(blank=True, default=list)),
                ('drone_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='osint_geospy.droneimage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
