# Generated by Django 4.2.10 on 2025-04-27 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osint_geospy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='droneimage',
            name='backend_image_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
