version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: backend
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - geospy-network
    # Temporarily disable healthcheck until we resolve the issues
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8000/api/session/health"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3
    #   start_period: 20s

  # Django Frontend Service
  django_frontend:
    build:
      context: .
      dockerfile: Dockerfile
    command: django_frontend
    volumes:
      - ./data:/app/data
      - ./src/django_frontend:/app/src/django_frontend
      - ./src/django_frontend/media:/app/src/django_frontend/media
      - ./src/django_frontend/static:/app/src/django_frontend/static
    ports:
      - "8080:8080"
    environment:
      - API_URL=http://backend:8000
      - WAIT_FOR_BACKEND=true
      - DJANGO_SETTINGS_MODULE=drone_geospy.settings
      - DJANGO_DEBUG=true
    env_file:
      - .env
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - geospy-network

  # Optional: Add a proxy service for production deployment
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - backend
  #     - django_frontend
  #   networks:
  #     - geospy-network

# Define a network
networks:
  geospy-network:
    driver: bridge 