version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: backend
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - geospy-network
    # Temporarily disable healthcheck until we resolve the issues
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8000/api/session/health"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3
    #   start_period: 20s

  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    command: frontend
    volumes:
      - ./data:/app/data
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000
      - WAIT_FOR_BACKEND=true
      # Añadir configuración para Streamlit
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ENABLE_CORS=false
    env_file:
      - .env
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - geospy-network

  # Optional: Add a proxy service for production deployment
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - backend
  #     - frontend
  #   networks:
  #     - geospy-network

# Define a network
networks:
  geospy-network:
    driver: bridge 